# Nome do Workflow
name: DevOpsLab Pipeline

# Evento que irá acionar a pipeline
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Requirements
        run: pip install -r requirements-dev.txt

      - name: Unit Test
        run: python -m unittest -v

      - name: Run tox
        run: tox -e py

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Docker Login
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > key.json
          cat key.json | docker login -u _json_key --password-stdin '${{ vars.GOOGLE_ARTIFACT }}'

      - name: Build & Push Image
        run: |
          docker build -t ${{ vars.GOOGLE_ARTIFACT }}/${{ vars.GOOGLE_PROJECT_ID }}/${{ vars.GOOGLE_REPONAME }}/${{ vars.GOOGLE_MYAPP }}:latest .
          docker push ${{ vars.GOOGLE_ARTIFACT }}/${{ vars.GOOGLE_PROJECT_ID }}/${{ vars.GOOGLE_REPONAME }}/${{ vars.GOOGLE_MYAPP }}:latest

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3 # https://github.com/actions/checkout

      - name: Auth GCP
        uses: "google-github-actions/auth@v1" # https://github.com/google-github-actions/auth
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Cloud Run Deploy
        id: deploy
        run: |-
          gcloud run deploy ${{ vars.GOOGLE_MYAPP }} \
            --quiet \
            --region  ${{ vars.GOOGLE_REGION }} \
            --image ${{ vars.GOOGLE_ARTIFACT }}/${{ vars.GOOGLE_PROJECT_ID }}/${{ vars.GOOGLE_REPONAME }}/${{ vars.GOOGLE_MYAPP }}:latest \
            --platform managed \
            --allow-unauthenticated \
            --project ${{ vars.GOOGLE_PROJECT_ID }} \
            --format json
